version: "3.4"
services:
  gluetun-torrents:
    image: qmcgaw/private-internet-access
    container_name: gluetun-torrents
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 8112:8112/tcp # Deluge GUI
    volumes:
      - ${ROOT}/config/gluetun-torrents:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access
      # Time zone for accurate logs times
      - TZ=${VPNTZ_TORRENT} # time zone, defined in .env
      # All VPN providers
      - USER=${VPNUSER}
      # All VPN providers but Mullvad
      - PASSWORD=${VPNPASS}  
      # All VPN providers but Mullvad
      - REGION=${VPNREGION_TORRENT} 
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
    restart: unless-stopped

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    network_mode: service:gluetun-torrents # run on the vpn network
    environment:
      - PUID=${PUID}          # default user id, defined in .env
      - PGID=${PGID}          # default group id, defined in .env
      - TZ=${VPNTZ_TORRENT}   # time zone, defined in .env
    volumes:
      - ${ROOT}/data/torrents:/data/torrents    # downloads folder
      - ${ROOT}/config/deluge:/config           # config files
    restart: unless-stopped
    
  gluetun-usenet:
    image: qmcgaw/private-internet-access
    container_name: gluetun-usenet
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 7888:8888/tcp # HTTP proxy
      - 7388:8388/tcp # Shadowsocks
      - 7388:8388/udp # Shadowsocks
      - 7000:8000/tcp # Built-in HTTP control server
      - 7112:8080/tcp # SABnzb GUI
    volumes:
      - ${ROOT}/config/gluetun-usenet:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access
      # Time zone for accurate logs times
      - TZ=${VPNTZ_USENET} # time zone, defined in .env
      # All VPN providers
      - USER=${VPNUSER}
      # All VPN providers but Mullvad
      - PASSWORD=${VPNPASS}  
      # All VPN providers but Mullvad
      - REGION=${VPNREGION_USENET} 
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:gluetun-usenet # run on the vpn network
    environment:
      - PUID=${PUID}          # default user id, defined in .env
      - PGID=${PGID}          # default group id, defined in .env
      - TZ=${VPNTZ_USENET}    # time zone, defined in .env
    volumes:
      - ${ROOT}/data/usenet:/data/usenet        # downloads folder
      - ${ROOT}/config/sabnzbd:/config          # config files
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    extra_hosts:
      - "media:${MC_IP}"
    ports:
      - 8989:8989/tcp # GUI
    environment:
      - PUID=${PUID}  # default user id, defined in .env
      - PGID=${PGID}  # default group id, defined in .env
      - TZ=${TZ}      # time zone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config     # config files
      - ${ROOT}/data:/data                # data folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    extra_hosts:
      - "media:${MC_IP}"
    ports:
      - 7878:7878/tcp # GUI
    environment:
      - PUID=${PUID}  # default user id, defined in .env
      - PGID=${PGID}  # default group id, defined in .env
      - TZ=${TZ}      # time zone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config     # config files
      - ${ROOT}/data:/data                # data folder

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    restart: unless-stopped
    extra_hosts:
      - "media:${MC_IP}"
    ports:
      - 9696:9696/tcp # GUI
    environment:
      - PUID=${PUID}  # default user id, defined in .env
      - PGID=${PGID}  # default group id, defined in .env
      - TZ=${TZ}      # time zone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/prowlarr:/config     # config files

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}      # timezone, defined in .env
    ports:
      - 32400:32400/tcp # GUI
    volumes:
      - ${ROOT}/config/plex/db:/config                  # plex database
      - ${ROOT}/config/plex/transcode:/transcode        # temp transcoded files
      - ${ROOT}/data/media-library:/data/media-library  # media library

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    ports:
      - 6767:6767/tcp # GUI
    environment:
      - PUID=${PUID}  # default user id, defined in .env
      - PGID=${PGID}  # default group id, defined in .env
      - TZ=${TZ}      # time zone, defined in .env
      - UMASK_SET=022 # optional
    volumes:
      - ${ROOT}/config/bazarr:/config                   # config files
      - ${ROOT}/data/media-library/movies:/movies       # movies folder
      - ${ROOT}/data/media-library/tv:/tv               # tv shows folder
      
  organizr:
    container_name: organizr
    hostname: organizr
    image: organizr/organizr:latest
    restart: unless-stopped
    extra_hosts:
      - "media:${MC_IP}"
    ports:
      - 5555:80
    volumes:
      - ${ROOT}/config/organizr:/config
    environment:
      - PUID=${PUID}  # default user id, defined in .env
      - PGID=${PGID}  # default group id, defined in .env
      - TZ=${TZ}      # time zone, defined in .env